version: '3'

services:

  app:
    build: .
    container_name: lab2-tracing-distribuido-span
    ports:
      - "8080:8080"

  prometheus:
    container_name: prometheus
    hostname: prometheus
    restart: always
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
      container_name: grafana
      hostname: grafana
      restart: always
      image: grafana/grafana:latest
      ports:
        - 3000:3000
      depends_on:
        - prometheus

  jaeger: # all-in-one
      container_name: jaeger
      hostname: jaeger
      restart: always
      image: jaegertracing/all-in-one:latest
      ports:
        - 16686:16686
        - 14268
        - 14250

  otel-collector:
      container_name: otel-collector
      hostname: otel-collector
      restart: always
      image: otel/opentelemetry-collector:latest
      command: ["--config=/etc/otel-collector-config.yaml"]
      ports:
        - 4317:4317
        - 8888:8888
        - 8889:8889
      volumes:
        - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml

networks:
  weather-api-otel: